# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonghwa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contents',
            name='created_date',
            field=models.CharField(max_length=14),
        ),
    ]
