# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonghwa', '0002_auto_20171105_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='sub_index',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
