# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bonghwa', '0003_contents_sub_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contents',
            old_name='sub_index',
            new_name='mention_index',
        ),
        migrations.AddField(
            model_name='contents',
            name='mention_order',
            field=models.CharField(default='0', max_length=5),
        ),
    ]
