# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-05 11:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonghwa', '0005_auto_20180205_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contents',
            name='imagename',
        ),
    ]
