# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-02-18 07:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bonghwa', '0006_remove_contents_imagename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contents',
            old_name='file',
            new_name='image',
        ),
    ]
